import asyncio
import os
import sys
import uuid
from datetime import datetime, timedelta, timezone

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "backend"))

from sqlalchemy import select

from backend.app.core.database import async_session
from backend.app.models import User
from backend.app.models.ticket import Ticket
from backend.app.models.enums import TicketCategory, TicketStatus, UserRole

TICKETS = [
    # ── Technical Questions ──
    {
        "sender_email": "lisa.chen@university.edu",
        "sender_name": "Lisa Chen",
        "subject": "Cannot connect to campus Wi-Fi on my laptop",
        "body_text": "Hi, I've been trying to connect to the Eduroam network all morning but it keeps saying 'authentication failed'. I've reset my password twice. Please help!",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 1,
    },
    {
        "sender_email": "marcus.johnson@gmail.com",
        "sender_name": "Marcus Johnson",
        "subject": "VPN not working from home",
        "body_text": "I'm trying to access the library database from off-campus but the VPN client crashes on launch. I'm on Windows 11. Is there an alternative way to access?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 2,
    },
    {
        "sender_email": "aisha.patel@student.edu",
        "sender_name": "Aisha Patel",
        "subject": "Lecture recording not loading in Moodle",
        "body_text": "The recording for BIO201 Lecture 12 just shows a black screen with a spinning circle. I've tried Chrome and Firefox, cleared cache, still nothing. Other recordings work fine.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 1,
    },
    {
        "sender_email": "james.rodriguez@university.edu",
        "sender_name": "James Rodriguez",
        "subject": "Matlab license expired mid-semester",
        "body_text": "My Matlab installation says the license has expired, but I'm enrolled in ENG301 which requires it. The IT office said licenses renew automatically. Can someone fix this?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 10,
    },
    {
        "sender_email": "emma.wilson@university.edu",
        "sender_name": "Emma Wilson",
        "subject": "Printer in Building C keeps jamming",
        "body_text": "The HP printer on the 3rd floor of Building C has jammed 4 times today. I have a 20-page assignment due at 4pm and the other printers are all busy.",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 7,
    },
    {
        "sender_email": "david.kim@student.edu",
        "sender_name": "David Kim",
        "subject": "Two-factor authentication not sending codes",
        "body_text": "I've been trying to log into the student portal for an hour. The 2FA code never arrives on my phone. I checked, my number is correct in the system. Is there a workaround?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 0,
    },
    {
        "sender_email": "sophia.mueller@university.edu",
        "sender_name": "Sophia Müller",
        "subject": "Zoom keeps disconnecting during online lectures",
        "body_text": "Every 10-15 minutes my Zoom disconnects with error code 5003. My internet is stable (100Mbps fiber). I've reinstalled Zoom twice. Attending hybrid lectures is becoming impossible.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 4,
    },
    {
        "sender_email": "ryan.oconnor@gmail.com",
        "sender_name": "Ryan O'Connor",
        "subject": "Lab computer won't boot - black screen",
        "body_text": "Computer #14 in the CS lab just shows a black screen with a blinking cursor. I need it for my 2pm lab session. Can someone reboot it remotely or send a technician?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 5,
    },
    {
        "sender_email": "fatima.al-rashid@student.edu",
        "sender_name": "Fatima Al-Rashid",
        "subject": "Cannot install RStudio for stats course",
        "body_text": "I'm following the installation guide for STA202 but RStudio won't install on my Mac. It says 'developer cannot be verified'. I tried the terminal workaround from StackOverflow but no luck.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 3,
    },
    {
        "sender_email": "carlos.garcia@university.edu",
        "sender_name": "Carlos Garcia",
        "subject": "Email inbox not receiving external messages",
        "body_text": "People outside the university say their emails bounce back when they try to email me. University-internal emails come through fine. My inbox isn't full. What's going on?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 14,
    },
    {
        "sender_email": "olivia.brown@university.edu",
        "sender_name": "Olivia Brown",
        "subject": "OneDrive sync failing - storage full warning",
        "body_text": "My OneDrive says I'm at 101% of storage but I've only used about 2GB and the limit is 1TB. It's preventing me from saving new documents. Something seems bugged.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 2,
    },
    {
        "sender_email": "lucas.nguyen@student.edu",
        "sender_name": "Lucas Nguyen",
        "subject": "Programming environment setup for CS101",
        "body_text": "I'm a freshman trying to set up Python and VS Code for CS101. The instructions say to use Anaconda but the download keeps failing at 90%. Can I just use regular Python instead?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 20,
    },
    {
        "sender_email": "hannah.smith@gmail.com",
        "sender_name": "Hannah Smith",
        "subject": "Gradescope won't accept my PDF submission",
        "body_text": "I've tried uploading my assignment to Gradescope six times. Every time it says 'invalid file format' even though it's definitely a PDF exported from Word. The deadline is tonight!",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 1,
    },
    {
        "sender_email": "omar.hassan@university.edu",
        "sender_name": "Omar Hassan",
        "subject": "Turnitin submission error 503",
        "body_text": "When I try to submit my dissertation chapter through Turnitin I get error 503. It's been like this for 2 days. My supervisor says the deadline won't be extended for technical issues.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 1,
    },
    {
        "sender_email": "amelia.clark@student.edu",
        "sender_name": "Amelia Clark",
        "subject": "Password reset link expired immediately",
        "body_text": "I requested a password reset, got the email, clicked the link within 30 seconds, and it said 'link expired'. I've tried 3 times now. I'm locked out of my account completely.",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 6,
    },

    # ── Refund Requests ──
    {
        "sender_email": "ethan.wright@university.edu",
        "sender_name": "Ethan Wright",
        "subject": "Double charged for tuition this semester",
        "body_text": "I checked my bank statement and there are two identical charges of $8,500 for Fall 2026 tuition. I only enrolled once. Please refund the duplicate charge immediately.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 3,
    },
    {
        "sender_email": "zoe.taylor@gmail.com",
        "sender_name": "Zoe Taylor",
        "subject": "Refund for dropped course - BUS305",
        "body_text": "I dropped BUS305 within the add/drop period (September 5th) but still haven't received a refund. The bursar's office told me to contact IT support. Please process this.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 15,
    },
    {
        "sender_email": "noah.anderson@student.edu",
        "sender_name": "Noah Anderson",
        "subject": "Parking permit refund request",
        "body_text": "I bought an annual parking permit in August but I'm transferring to another university next month. I was told I'd get a prorated refund. How do I request it?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 30,
    },
    {
        "sender_email": "mia.thompson@university.edu",
        "sender_name": "Mia Thompson",
        "subject": "Meal plan overcharge - charged for premium plan",
        "body_text": "I signed up for the Basic meal plan ($2,200/semester) but my account shows I'm on the Premium plan ($3,800/semester). I never selected Premium. Please refund the difference.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 5,
    },
    {
        "sender_email": "liam.jackson@gmail.com",
        "sender_name": "Liam Jackson",
        "subject": "Library fine refund - book already returned",
        "body_text": "I have a $45 fine on my account for 'Introduction to Macroeconomics' but I returned that book on October 2nd. The return receipt is attached to my student portal. Please remove the fine.",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 12,
    },
    {
        "sender_email": "isabella.lee@university.edu",
        "sender_name": "Isabella Lee",
        "subject": "Graduation fee refund - cancelled ceremony attendance",
        "body_text": "I paid the $150 graduation ceremony fee but I won't be able to attend due to a family emergency. Can I get a refund since it's 3 weeks before the ceremony?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 8,
    },
    {
        "sender_email": "alexander.martinez@student.edu",
        "sender_name": "Alexander Martinez",
        "subject": "Gym membership refund after injury",
        "body_text": "I broke my ankle and can't use the gym for the rest of the semester. I paid $120 for the full semester pass. Is there a medical exception refund policy?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 40,
    },
    {
        "sender_email": "charlotte.davis@university.edu",
        "sender_name": "Charlotte Davis",
        "subject": "Duplicate payment for summer housing",
        "body_text": "My summer housing payment of $1,600 was processed twice on June 1st. I've been waiting 3 weeks for a resolution. This is causing me financial hardship.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 25,
    },
    {
        "sender_email": "benjamin.wilson@gmail.com",
        "sender_name": "Benjamin Wilson",
        "subject": "Online course fee refund - course cancelled",
        "body_text": "I paid $600 for PSYCH101 Online but I just got an email saying the course was cancelled due to low enrollment. When will I get my money back?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 18,
    },
    {
        "sender_email": "harper.garcia@student.edu",
        "sender_name": "Harper Garcia",
        "subject": "Transcript fee refund - wrong version ordered",
        "body_text": "I accidentally ordered 5 official transcripts ($75) instead of unofficial ones (free). I realized immediately and emailed but no one responded. Please refund and cancel the order.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 4,
    },
    {
        "sender_email": "elijah.robinson@university.edu",
        "sender_name": "Elijah Robinson",
        "subject": "Study abroad deposit refund",
        "body_text": "My study abroad program to Barcelona was cancelled by the university. I paid a $500 deposit in March. When will deposits be returned to affected students?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 35,
    },
    {
        "sender_email": "ava.white@gmail.com",
        "sender_name": "Ava White",
        "subject": "Overcharged for printing credits",
        "body_text": "My printing account shows I used 850 pages this month. I printed maybe 50 pages max. Someone else must be using my account. Please refund the $42 overcharge.",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 22,
    },
    {
        "sender_email": "william.harris@student.edu",
        "sender_name": "William Harris",
        "subject": "Health insurance fee waiver refund",
        "body_text": "I submitted a health insurance waiver in August because I have my own coverage. The waiver was approved but I was still charged $1,200 for the university plan. Please refund this.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 50,
    },
    {
        "sender_email": "scarlett.martin@university.edu",
        "sender_name": "Scarlett Martin",
        "subject": "Late fee refund - system error prevented payment",
        "body_text": "I tried to pay my tuition before the deadline but the payment portal was down for maintenance all day. Now I have a $100 late fee. I have screenshots of the error. Please waive it.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 9,
    },
    {
        "sender_email": "logan.thompson@gmail.com",
        "sender_name": "Logan Thompson",
        "subject": "Club registration fee refund - club dissolved",
        "body_text": "I paid $30 to join the Photography Club but I got an email saying the club was dissolved due to lack of faculty advisor. When do I get my registration fee back?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 60,
    },

    # ── General Questions ──
    {
        "sender_email": "grace.king@university.edu",
        "sender_name": "Grace King",
        "subject": "How do I declare a minor in Data Science?",
        "body_text": "I'm a sophomore in the Business program and I want to add a Data Science minor. What's the process? Do I need my advisor's signature or can I do it online?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 16,
    },
    {
        "sender_email": "henry.adams@student.edu",
        "sender_name": "Henry Adams",
        "subject": "When do dorm move-in dates get announced?",
        "body_text": "I'm an incoming freshman and I haven't received any information about when I can move into my dorm. I need to book flights. Is there a tentative date I can plan around?",
        "status": TicketStatus.CLOSED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 70,
    },
    {
        "sender_email": "chloe.baker@university.edu",
        "sender_name": "Chloe Baker",
        "subject": "Where do I pick up my student ID card?",
        "body_text": "I uploaded my photo last week but I don't know where to collect the physical card. The website says 'awaiting pickup' but doesn't specify a location. Which building?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 11,
    },
    {
        "sender_email": "jack.allen@gmail.com",
        "sender_name": "Jack Allen",
        "subject": "Can I take more than 18 credits this semester?",
        "body_text": "I'm trying to graduate early and I need to take 21 credits this semester. Is there a way to get an override for the credit limit? My GPA is 3.8 if that helps.",
        "status": TicketStatus.CLOSED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 45,
    },
    {
        "sender_email": "ella.turner@student.edu",
        "sender_name": "Ella Turner",
        "subject": "What are the internship credit requirements?",
        "body_text": "I got a summer internship at a tech company and I want to know if it qualifies for academic credit. How many hours do I need to work? What paperwork is required?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 6,
    },
    {
        "sender_email": "daniel.scott@university.edu",
        "sender_name": "Daniel Scott",
        "subject": "How to request a transcript for grad school applications",
        "body_text": "I'm applying to grad schools and most of them require official transcripts. How do I order them through the university? How long does it take and what's the cost?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 28,
    },
    {
        "sender_email": "aria.mitchell@gmail.com",
        "sender_name": "Aria Mitchell",
        "subject": "Commencement ceremony details for family",
        "body_text": "My parents are coming from overseas for graduation. How many guest tickets does each student get? Is the ceremony outdoors? My mom has mobility issues - is there accessible seating?",
        "status": TicketStatus.CLOSED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 80,
    },
    {
        "sender_email": "leo.carter@student.edu",
        "sender_name": "Leo Carter",
        "subject": "Do I need a parking permit for evening classes only?",
        "body_text": "All my classes are after 5pm. I heard parking is free after 4pm but I want to confirm before I get a ticket. Should I still buy a permit to be safe?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 13,
    },
    {
        "sender_email": "layla.reed@university.edu",
        "sender_name": "Layla Reed",
        "subject": "How does the pass/fail option work for electives?",
        "body_text": "I'm considering taking a difficult elective pass/fail so it doesn't hurt my GPA. Is there a deadline to switch? Does it affect financial aid or scholarships?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 2,
    },
    {
        "sender_email": "matthew.cook@gmail.com",
        "sender_name": "Matthew Cook",
        "subject": "Can I use the gym during winter break?",
        "body_text": "I'm staying on campus over winter break and want to keep going to the gym. Do the recreation facilities stay open? Are hours reduced? Do I need a separate pass?",
        "status": TicketStatus.CLOSED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 55,
    },
    {
        "sender_email": "avery.ross@student.edu",
        "sender_name": "Avery Ross",
        "subject": "How to change my major from Biology to Chemistry",
        "body_text": "After two semesters I realized chemistry is more my thing. What's the process for changing majors? Will my biology credits transfer? Who do I need to talk to?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 32,
    },
    {
        "sender_email": "penelope.rivera@university.edu",
        "sender_name": "Penelope Rivera",
        "subject": "Guest wifi access for visiting family",
        "body_text": "My parents are visiting this weekend. Is there a guest wifi network they can use on campus? Do they need to register or is there a temporary password?",
        "status": TicketStatus.CLOSED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 65,
    },
    {
        "sender_email": "samuel.peterson@gmail.com",
        "sender_name": "Samuel Peterson",
        "subject": "Study abroad application deadline for Spring 2027",
        "body_text": "I'm interested in the Tokyo exchange program for Spring 2027. When is the application deadline? What's the minimum GPA requirement? Are scholarships available?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 7,
    },
    {
        "sender_email": "nora.hall@student.edu",
        "sender_name": "Nora Hall",
        "subject": "Accommodations for student with ADHD during exams",
        "body_text": "I was recently diagnosed with ADHD and I need to know what accommodations are available for exams. How do I register with the disability services office?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 19,
    },
    {
        "sender_email": "sebastian.morales@university.edu",
        "sender_name": "Sebastian Morales",
        "subject": "How to apply for on-campus jobs",
        "body_text": "I'm looking for a part-time job on campus. Is there a job board or portal? What positions are typically available for undergrads? Do I need work-study eligibility?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 4,
    },
    {
        "sender_email": "stella.wood@gmail.com",
        "sender_name": "Stella Wood",
        "subject": "Library book renewal limit",
        "body_text": "I have a book checked out for a research paper and I've already renewed it twice. Can I renew it again or do I need to return and re-check it out? What happens if someone else requests it?",
        "status": TicketStatus.CLOSED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 48,
    },
]

# ── Extra tickets to reach 100 (blank category = uncategorized) ──
EXTRA_TICKETS = [
    {
        "sender_email": "elena.petrov@university.edu",
        "sender_name": "Elena Petrov",
        "subject": "Canvas grade shows different from what professor announced",
        "body_text": "Professor Davis said I got an 87 on the midterm but Canvas shows 72. I have the graded paper with the score written on it. Can someone fix the system entry?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 2,
    },
    {
        "sender_email": "joshua.nelson@gmail.com",
        "sender_name": "Joshua Nelson",
        "subject": "Building access card not working on weekends",
        "body_text": "My access card opens the CS building fine during weekdays but doesn't work on Saturdays. I need weekend access for a group project. Can you update my permissions?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 3,
    },
    {
        "sender_email": "nadia.hussein@student.edu",
        "sender_name": "Nadia Hussein",
        "subject": "How do I defer my admission by one semester?",
        "body_text": "I've been accepted for Fall 2026 but I need to defer to Spring 2027 for medical reasons. What's the process? Do I lose my scholarship if I defer?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 5,
    },
    {
        "sender_email": "conor.murphy@university.edu",
        "sender_name": "Conor Murphy",
        "subject": "Microphone not working in language lab",
        "body_text": "The headset at station 7 in the language lab has a broken microphone. I need it for my Spanish oral exam practice. Can someone swap or fix it?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 8,
    },
    {
        "sender_email": "yuki.tanaka@gmail.com",
        "sender_name": "Yuki Tanaka",
        "subject": "International student orientation schedule",
        "body_text": "I'm arriving from Japan on August 20th. Is there an international student orientation before regular orientation? Will someone pick me up from the airport?",
        "status": TicketStatus.CLOSED,
        "category": None,
        "days_ago": 85,
    },
    {
        "sender_email": "maya.jones@student.edu",
        "sender_name": "Maya Jones",
        "subject": "Scholarship disbursement delay",
        "body_text": "My Bright Futures scholarship usually disburses the first week of classes but it's now week 3 and still nothing. Rent is due. Is there a delay this semester?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 10,
    },
    {
        "sender_email": "finn.oconnell@university.edu",
        "sender_name": "Finn O'Connell",
        "subject": "Can't find my assigned academic advisor",
        "body_text": "I logged into the student portal but my advisor information is blank. I need to discuss my course schedule for next semester. How do I find out who my advisor is?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 17,
    },
    {
        "sender_email": "aria.kapoor@gmail.com",
        "sender_name": "Aria Kapoor",
        "subject": "Projector in room BH-204 is blurry",
        "body_text": "I'm presenting my thesis tomorrow in BH-204 but the projector is completely out of focus and the remote doesn't work. Can facilities check it before 10am tomorrow?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 4,
    },
    {
        "sender_email": "miles.richardson@student.edu",
        "sender_name": "Miles Richardson",
        "subject": "How do I get a locker in the gym?",
        "body_text": "I see people using lockers in the gym changing room. Are they assigned or first-come-first-served? Is there a rental fee? Mine keeps getting broken into.",
        "status": TicketStatus.CLOSED,
        "category": None,
        "days_ago": 58,
    },
    {
        "sender_email": "clara.nguyen@university.edu",
        "sender_name": "Clara Nguyen",
        "subject": "Can I record lectures for personal use?",
        "body_text": "I have a learning disability that makes note-taking difficult. Am I allowed to record lectures on my phone? Do I need permission from each professor or just the disability office?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 23,
    },
    {
        "sender_email": "theo.wagner@gmail.com",
        "sender_name": "Theo Wagner",
        "subject": "Fire alarm keeps going off in my dorm",
        "body_text": "The fire alarm in Morrison Hall has gone off 4 times this week between 2am and 4am. No actual fire. This is severely affecting my sleep and exam performance.",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 3,
    },
    {
        "sender_email": "layla.fernandez@student.edu",
        "sender_name": "Layla Fernandez",
        "subject": "Need a letter of enrollment for visa application",
        "body_text": "I need an official enrollment verification letter for my student visa renewal. The immigration office needs it within 2 weeks. Who issues this and how long does it take?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 26,
    },
    {
        "sender_email": "oscar.washington@university.edu",
        "sender_name": "Oscar Washington",
        "subject": "Bus shuttle schedule changed without notice",
        "body_text": "The campus shuttle between North and South campus used to run every 15 minutes. Now it seems completely random. I was late to class twice. Is there a new schedule posted?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 6,
    },
    {
        "sender_email": "ivy.green@gmail.com",
        "sender_name": "Ivy Green",
        "subject": "Graduation application status check",
        "body_text": "I submitted my graduation application 3 weeks ago but the portal still says 'under review'. Commencement is in 6 weeks. Will I hear back in time to order my cap and gown?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 21,
    },
    {
        "sender_email": "axel.andersson@student.edu",
        "sender_name": "Axel Andersson",
        "subject": "Exchange student course registration issue",
        "body_text": "I'm an exchange student from Sweden. The system won't let me register for courses because it says I have a 'registration hold'. No one told me what this means or how to clear it.",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 7,
    },
    {
        "sender_email": "zara.khan@university.edu",
        "sender_name": "Zara Khan",
        "subject": "Can't see my final exam schedule",
        "body_text": "The exam schedule page in the portal shows 'no data available' even though exams are in 3 weeks. Other students in my classes can see their schedules. What's wrong with my account?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 8,
    },
    {
        "sender_email": "kai.yamamoto@gmail.com",
        "sender_name": "Kai Yamamoto",
        "subject": "How to report a Title IX violation",
        "body_text": "I need to report an incident but I'm not sure about the process. Is there a confidential way to file a report? Who handles these cases on campus?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 33,
    },
    {
        "sender_email": "ruby.collins@student.edu",
        "sender_name": "Ruby Collins",
        "subject": "Student discount for Adobe Creative Cloud",
        "body_text": "I heard students get free or discounted Adobe Creative Cloud. How do I activate this with my student email? The Adobe website asks for a school code.",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 15,
    },
    {
        "sender_email": "felix.hoffman@university.edu",
        "sender_name": "Felix Hoffman",
        "subject": "Thesis formatting requirements",
        "body_text": "I'm about to submit my master's thesis. Where can I find the official formatting guidelines? I need specifics on margins, font size, citation style, and page numbering.",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 9,
    },
    {
        "sender_email": "sadie.williams@gmail.com",
        "sender_name": "Sadie Williams",
        "subject": "Course evaluation survey link broken",
        "body_text": "The email says complete course evaluations by Friday but the link redirects to a 404 page. Tried on Chrome, Safari, and my phone. Please send a working link.",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 1,
    },
    {
        "sender_email": "luca.romano@student.edu",
        "sender_name": "Luca Romano",
        "subject": "Mentorship program application",
        "body_text": "I'm interested in the alumni mentorship program I heard about at orientation. Where do I apply? Is it open to sophomores or only juniors and seniors?",
        "status": TicketStatus.CLOSED,
        "category": None,
        "days_ago": 72,
    },
    {
        "sender_email": "eva.andersen@university.edu",
        "sender_name": "Eva Andersen",
        "subject": "Emergency grant application for unexpected expenses",
        "body_text": "My laptop broke and I can't afford to replace it. I heard there's an emergency grant fund for students in financial hardship. How do I apply and what documentation do I need?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 11,
    },
    {
        "sender_email": "nathan.brooks@gmail.com",
        "sender_name": "Nathan Brooks",
        "subject": "Research lab access after hours",
        "body_text": "I'm working on my senior thesis and often need lab access past 10pm when the building locks. How do I get after-hours access to the biology research lab?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 24,
    },
    {
        "sender_email": "isla.macdonald@student.edu",
        "sender_name": "Isla MacDonald",
        "subject": "Can't view my tuition bill breakdown",
        "body_text": "When I click 'View Bill' in the student portal it shows the total but no breakdown. I need to see the itemized charges to dispute a fee. How can I get a detailed invoice?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 6,
    },
    {
        "sender_email": "diego.flores@university.edu",
        "sender_name": "Diego Flores",
        "subject": "How to join a research group as an undergrad",
        "body_text": "I'm a sophomore in mechanical engineering and I'd really like to get involved in research. How do I find professors looking for undergrad assistants? Is there a listing?",
        "status": TicketStatus.CLOSED,
        "category": None,
        "days_ago": 68,
    },
    {
        "sender_email": "poppy.hughes@gmail.com",
        "sender_name": "Poppy Hughes",
        "subject": "Not receiving university emergency alerts",
        "body_text": "My roommate gets text alerts for campus emergencies and weather closures but I don't. I checked my profile - my phone number is correct. How do I opt in?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 14,
    },
    {
        "sender_email": "juan.cruz@student.edu",
        "sender_name": "Juan Cruz",
        "subject": "Transfer credits not showing on transcript",
        "body_text": "I transferred from community college with 45 credits but my transcript only shows 30. I sent all my official transcripts months ago. The missing credits are prerequisites for my major.",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 12,
    },
    {
        "sender_email": "olive.marshall@university.edu",
        "sender_name": "Olive Marshall",
        "subject": "Can I bring my emotional support animal to class?",
        "body_text": "I have an approved emotional support animal (a small dog). Am I allowed to bring her to lectures and the library? What documentation do I need to show if asked?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 37,
    },
    {
        "sender_email": "rory.ellis@gmail.com",
        "sender_name": "Rory Ellis",
        "subject": "How to get a copy of my high school transcript",
        "body_text": "A scholarship application requires my high school transcript. I submitted it when I applied to university. Is it still on file somewhere or do I need to contact my high school?",
        "status": TicketStatus.CLOSED,
        "category": None,
        "days_ago": 52,
    },
    {
        "sender_email": "elle.park@student.edu",
        "sender_name": "Elle Park",
        "subject": "Canvas not showing this semester's courses",
        "body_text": "I enrolled in 5 courses last week but my Canvas dashboard is still empty. It shows 'no courses' under Current Enrollments. The add/drop deadline is next week. Please help.",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 4,
    },
    {
        "sender_email": "julian.vargas@university.edu",
        "sender_name": "Julian Vargas",
        "subject": "Smoke smell in library study room",
        "body_text": "Study room 3B on the second floor of the library smells strongly of cigarette smoke. It's giving me headaches. Is there a way to report this to facilities?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 5,
    },
    {
        "sender_email": "maeve.sullivan@gmail.com",
        "sender_name": "Maeve Sullivan",
        "subject": "Need a notary for financial aid documents",
        "body_text": "My financial aid office requires notarized documents but I don't know where to find a notary on campus. Does the university offer free notary services for students?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 27,
    },
    {
        "sender_email": "xavier.owens@student.edu",
        "sender_name": "Xavier Owens",
        "subject": "Vending machine ate my money",
        "body_text": "The snack machine in the student center took $3.50 and didn't dispense anything. This is the third time this month. Can I get a refund and can someone please fix it?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 2,
    },
    {
        "sender_email": "quinn.bell@university.edu",
        "sender_name": "Quinn Bell",
        "subject": "Withdraw from a course after deadline - medical reasons",
        "body_text": "I was hospitalized last week and missed the course withdrawal deadline by 2 days. I can provide medical documentation. Is there a late withdrawal petition process?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 5,
    },
    {
        "sender_email": "cecily.watson@gmail.com",
        "sender_name": "Cecily Watson",
        "subject": "Student health center appointment",
        "body_text": "I've been trying to book an appointment at the health center for 2 weeks but there are never any slots available online. Do they take walk-ins? I have a persistent cough.",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 3,
    },
    {
        "sender_email": "damon.powell@student.edu",
        "sender_name": "Damon Powell",
        "subject": "How to dispute a parking ticket",
        "body_text": "I got a $60 parking ticket but I was parked in a valid student lot with my permit displayed. The ticket says 'no permit visible'. How do I appeal this with photo evidence?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 18,
    },
    {
        "sender_email": "willa.ross@university.edu",
        "sender_name": "Willa Ross",
        "subject": "Elevator in humanities building out of order",
        "body_text": "The elevator in the Humanities building has been out of order for 4 days. I use a wheelchair and my classes are on the 3rd floor. Is there an alternative accessible route?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 4,
    },
    {
        "sender_email": "leon.hoffmann@gmail.com",
        "sender_name": "Leon Hoffmann",
        "subject": "Requesting a private study room in the library",
        "body_text": "I have ADHD and need a quiet, distraction-free space for exams. How do I reserve one of the private study rooms in the library? Can I book recurring slots?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 20,
    },
    {
        "sender_email": "freyja.larsen@student.edu",
        "sender_name": "Freyja Larsen",
        "subject": "Financial aid package reduced without explanation",
        "body_text": "My financial aid for this semester was reduced by $2,000 compared to last semester but my family's income hasn't changed. I can't afford the gap. Who do I talk to?",
        "status": TicketStatus.OPEN,
        "category": None,
        "days_ago": 13,
    },
    {
        "sender_email": "orlando.diaz@university.edu",
        "sender_name": "Orlando Diaz",
        "subject": "Can international students work off-campus?",
        "body_text": "I'm on an F-1 visa and want to do an off-campus internship next summer. Do I need CPT or OPT authorization? How long does the approval process take?",
        "status": TicketStatus.CLOSED,
        "category": None,
        "days_ago": 90,
    },
]

ADDITIONAL_TICKETS = [
    {
        "sender_email": "isaac.ford@university.edu",
        "sender_name": "Isaac Ford",
        "subject": "How to access alumni career services",
        "body_text": "I graduated last semester but I heard alumni can still use career services for up to a year. How do I schedule a career counseling appointment as an alum?",
        "status": TicketStatus.CLOSED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 42,
    },
    {
        "sender_email": "aria.zhu@student.edu",
        "sender_name": "Aria Zhu",
        "subject": "How to report a broken window in my dorm",
        "body_text": "My dorm window has a large crack that's letting cold air in. It's been like this since I moved in. Can someone come replace the glass before winter?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 29,
    },
    {
        "sender_email": "blake.henderson@gmail.com",
        "sender_name": "Blake Henderson",
        "subject": "Schedule conflict - two exams at the same time",
        "body_text": "My final exam schedule shows both CHEM202 and MATH301 on December 14th at 9am. How is this possible? Can one be rescheduled or do I take them back to back?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 10,
    },
    {
        "sender_email": "naomi.clarke@university.edu",
        "sender_name": "Naomi Clarke",
        "subject": "Can't log into library databases from off-campus",
        "body_text": "When I try to access JSTOR or ProQuest from home, it asks for a login but doesn't accept my university credentials. The proxy server seems broken. I have a paper due Monday.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 1,
    },
    {
        "sender_email": "aaron.prasad@student.edu",
        "sender_name": "Aaron Prasad",
        "subject": "Reimbursement for academic conference travel",
        "body_text": "I presented at a conference last month and submitted my travel receipts 3 weeks ago. The finance department says they never received them. I have the confirmation email.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 21,
    },
    {
        "sender_email": "genevieve.lynch@gmail.com",
        "sender_name": "Genevieve Lynch",
        "subject": "How to reset my MFA device after losing phone",
        "body_text": "I lost my phone yesterday which had my authenticator app for MFA. I can't log into anything. How do I reset my MFA and register a new device before my exam at 3pm?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 3,
    },
    {
        "sender_email": "rhett.campbell@university.edu",
        "sender_name": "Rhett Campbell",
        "subject": "Can I switch sections for the same course?",
        "body_text": "I'm in Professor Johnson's section of HIST101 at 8am but I'd like to switch to Professor Lee's section at 11am. Are there open spots and is it possible mid-semester?",
        "status": TicketStatus.CLOSED,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 47,
    },
    {
        "sender_email": "valentina.rivera@student.edu",
        "sender_name": "Valentina Rivera",
        "subject": "How do I check my meal plan balance?",
        "body_text": "I can't find anywhere on the student portal that shows my remaining meal swipes and dining dollars. The dining hall staff couldn't help either. Where is this information?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 16,
    },
    {
        "sender_email": "beau.daniels@university.edu",
        "sender_name": "Beau Daniels",
        "subject": "Refund for duplicate textbook purchase",
        "body_text": "I accidentally ordered the same textbook twice from the campus bookstore online. I returned the second copy in-store but never received the $95 refund to my card.",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.REFUND_REQUEST,
        "days_ago": 7,
    },
    {
        "sender_email": "mira.cho@gmail.com",
        "sender_name": "Mira Cho",
        "subject": "How to get a student software license for SPSS",
        "body_text": "My stats course requires SPSS but the university software page says 'no licenses available' for students. The professor said IT handles this. How do I get access?",
        "status": TicketStatus.RESOLVED,
        "category": TicketCategory.TECHNICAL_QUESTION,
        "days_ago": 13,
    },
    {
        "sender_email": "hector.montoya@student.edu",
        "sender_name": "Hector Montoya",
        "subject": "Requesting a leave of absence for Spring 2027",
        "body_text": "I need to take a semester off for personal reasons. What's the process for requesting a leave of absence? Will it affect my enrollment status or financial aid eligibility?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 8,
    },
    {
        "sender_email": "imogen.wells@university.edu",
        "sender_name": "Imogen Wells",
        "subject": "My student email signature has someone else's name",
        "body_text": "When I send emails from my university account, the signature block says 'Dr. Patricia Wallace, Department of Sociology'. That's definitely not me. How do I fix my display name?",
        "status": TicketStatus.RESOLVED,
        "category": None,
        "days_ago": 9,
    },
    {
        "sender_email": "cole.fisher@gmail.com",
        "sender_name": "Cole Fisher",
        "subject": "Vendor setup for student organization event",
        "body_text": "Our student org is hosting a career fair and we want to have food vendors on campus. What's the process for getting vendor permits and access to electricity in the quad?",
        "status": TicketStatus.OPEN,
        "category": TicketCategory.GENERAL_QUESTION,
        "days_ago": 12,
    },
    {
        "sender_email": "delilah.knight@student.edu",
        "sender_name": "Delilah Knight",
        "subject": "How to get a replacement diploma",
        "body_text": "My diploma was damaged during a move. The frame broke and the certificate is torn. Can I order a replacement? What's the fee and how long does it take?",
        "status": TicketStatus.CLOSED,
        "category": None,
        "days_ago": 62,
    },
]

ALL_TICKETS = TICKETS + EXTRA_TICKETS + ADDITIONAL_TICKETS

# ── Assignee rotation: spread tickets across unassigned, admin, and agent ──
# assigned_to index: 0 = unassigned, 1 = admin, 2 = agent
ASSIGNEE_INDEX = []
for i in range(100):
    if i < 25:
        ASSIGNEE_INDEX.append(0)  # first 25 unassigned
    elif i < 55:
        ASSIGNEE_INDEX.append(1)  # next 30 admin
    elif i < 80:
        ASSIGNEE_INDEX.append(2)  # next 25 agent
    else:
        ASSIGNEE_INDEX.append(0)  # last 20 unassigned


async def seed():
    async with async_session() as db:
        result = await db.execute(select(User))
        users = {u.email: u for u in result.scalars().all()}

        if not users:
            print("No users found. Run seed.py first to create admin, then run setup_db.py to create agent.")
            return

        admin = [u for u in users.values() if u.role == UserRole.ADMIN]
        agents = [u for u in users.values() if u.role == UserRole.AGENT]
        admin_id = admin[0].id if admin else None
        agent_id = agents[0].id if agents else None

        print(f"Found {len(users)} users: {len(admin)} admin, {len(agents)} agent(s)")

        assignee_map = {0: None, 1: admin_id, 2: agent_id}

        now = datetime.now(timezone.utc)

        count = 0
        for i, t in enumerate(ALL_TICKETS):
            created = now - timedelta(days=t["days_ago"])
            # updated is always >= created (some resolved tickets were updated later)
            updated_offset = min(t["days_ago"] - 1, t["days_ago"] // 2) if t["days_ago"] > 1 else 0
            updated = now - timedelta(days=updated_offset)

            ticket = Ticket(
                sender_email=t["sender_email"],
                sender_name=t["sender_name"],
                subject=t["subject"],
                body_text=t["body_text"],
                status=t["status"],
                category=t["category"],
                assigned_to=assignee_map[ASSIGNEE_INDEX[i]],
                created_at=created,
                updated_at=updated,
            )
            db.add(ticket)
            count += 1

        await db.commit()
        print(f"Created {count} tickets.")


if __name__ == "__main__":
    asyncio.run(seed())
