"""add_new_and_processing_ticket_status

Revision ID: 52eb5882ff97
Revises: ce42e491aef1
Create Date: 2026-07-30 14:07:38.313826
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '52eb5882ff97'
down_revision: Union[str, None] = 'ce42e491aef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
