"""add body_html to ticket_replies

Revision ID: 7a5861b77746
Revises: a1b2c3d4e5f6
Create Date: 2026-07-27 17:47:48.554843
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a5861b77746'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_replies', sa.Column('body_html', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('ticket_replies', 'body_html')
    # ### end Alembic commands ###
