"""add ondelete behavior to foreign keys

Revision ID: ce42e491aef1
Revises: 7a5861b77746
Create Date: 2026-07-27 18:40:30.535623
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce42e491aef1'
down_revision: Union[str, None] = '7a5861b77746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ticket_replies_author_id_fkey'), 'ticket_replies', type_='foreignkey')
    op.drop_constraint(op.f('ticket_replies_ticket_id_fkey'), 'ticket_replies', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_replies', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ticket_replies', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('tickets_assigned_to_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_assigned_to_fkey'), 'tickets', 'users', ['assigned_to'], ['id'])
    op.drop_constraint(None, 'ticket_replies', type_='foreignkey')
    op.drop_constraint(None, 'ticket_replies', type_='foreignkey')
    op.create_foreign_key(op.f('ticket_replies_ticket_id_fkey'), 'ticket_replies', 'tickets', ['ticket_id'], ['id'])
    op.create_foreign_key(op.f('ticket_replies_author_id_fkey'), 'ticket_replies', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
